require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cut_names", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CutName. As you add validations to CutName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CutName.create! valid_attributes
      get cut_names_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cut_name = CutName.create! valid_attributes
      get cut_name_url(cut_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cut_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cut_name = CutName.create! valid_attributes
      get edit_cut_name_url(cut_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CutName" do
        expect {
          post cut_names_url, params: { cut_name: valid_attributes }
        }.to change(CutName, :count).by(1)
      end

      it "redirects to the created cut_name" do
        post cut_names_url, params: { cut_name: valid_attributes }
        expect(response).to redirect_to(cut_name_url(CutName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CutName" do
        expect {
          post cut_names_url, params: { cut_name: invalid_attributes }
        }.to change(CutName, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cut_names_url, params: { cut_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cut_name" do
        cut_name = CutName.create! valid_attributes
        patch cut_name_url(cut_name), params: { cut_name: new_attributes }
        cut_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cut_name" do
        cut_name = CutName.create! valid_attributes
        patch cut_name_url(cut_name), params: { cut_name: new_attributes }
        cut_name.reload
        expect(response).to redirect_to(cut_name_url(cut_name))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cut_name = CutName.create! valid_attributes
        patch cut_name_url(cut_name), params: { cut_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cut_name" do
      cut_name = CutName.create! valid_attributes
      expect {
        delete cut_name_url(cut_name)
      }.to change(CutName, :count).by(-1)
    end

    it "redirects to the cut_names list" do
      cut_name = CutName.create! valid_attributes
      delete cut_name_url(cut_name)
      expect(response).to redirect_to(cut_names_url)
    end
  end
end
