require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pieces", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Piece. As you add validations to Piece, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Piece.create! valid_attributes
      get pieces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      piece = Piece.create! valid_attributes
      get piece_url(piece)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_piece_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      piece = Piece.create! valid_attributes
      get edit_piece_url(piece)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Piece" do
        expect {
          post pieces_url, params: { piece: valid_attributes }
        }.to change(Piece, :count).by(1)
      end

      it "redirects to the created piece" do
        post pieces_url, params: { piece: valid_attributes }
        expect(response).to redirect_to(piece_url(Piece.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Piece" do
        expect {
          post pieces_url, params: { piece: invalid_attributes }
        }.to change(Piece, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pieces_url, params: { piece: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested piece" do
        piece = Piece.create! valid_attributes
        patch piece_url(piece), params: { piece: new_attributes }
        piece.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the piece" do
        piece = Piece.create! valid_attributes
        patch piece_url(piece), params: { piece: new_attributes }
        piece.reload
        expect(response).to redirect_to(piece_url(piece))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        piece = Piece.create! valid_attributes
        patch piece_url(piece), params: { piece: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested piece" do
      piece = Piece.create! valid_attributes
      expect {
        delete piece_url(piece)
      }.to change(Piece, :count).by(-1)
    end

    it "redirects to the pieces list" do
      piece = Piece.create! valid_attributes
      delete piece_url(piece)
      expect(response).to redirect_to(pieces_url)
    end
  end
end
