require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductType. As you add validations to ProductType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductType.create! valid_attributes
      get product_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_type = ProductType.create! valid_attributes
      get product_type_url(product_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product_type = ProductType.create! valid_attributes
      get edit_product_type_url(product_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductType" do
        expect {
          post product_types_url, params: { product_type: valid_attributes }
        }.to change(ProductType, :count).by(1)
      end

      it "redirects to the created product_type" do
        post product_types_url, params: { product_type: valid_attributes }
        expect(response).to redirect_to(product_type_url(ProductType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductType" do
        expect {
          post product_types_url, params: { product_type: invalid_attributes }
        }.to change(ProductType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post product_types_url, params: { product_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested product_type" do
        product_type = ProductType.create! valid_attributes
        patch product_type_url(product_type), params: { product_type: new_attributes }
        product_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the product_type" do
        product_type = ProductType.create! valid_attributes
        patch product_type_url(product_type), params: { product_type: new_attributes }
        product_type.reload
        expect(response).to redirect_to(product_type_url(product_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        product_type = ProductType.create! valid_attributes
        patch product_type_url(product_type), params: { product_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_type" do
      product_type = ProductType.create! valid_attributes
      expect {
        delete product_type_url(product_type)
      }.to change(ProductType, :count).by(-1)
    end

    it "redirects to the product_types list" do
      product_type = ProductType.create! valid_attributes
      delete product_type_url(product_type)
      expect(response).to redirect_to(product_types_url)
    end
  end
end
